[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/portal"
  status = 200
  conditions = {Host = ["clients.skripti.fi"]}

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
